# roles/static-ip/handlers/main.yml
---

- name: reboot
  reboot:
    reboot_timeout: 300

- name: wait for reboot to finish
  local_action: wait_for host={{ ipaddress }} state=started port=22 delay=50 timeout=120
  become: false
